language: node_js
node_js:
  - "node"
before_install:
  - npm install -g yarn
  - psql -c 'create database man_dev;' -U postgres
install:
  - yarn
script:
  - npm run build
  - npm run test
after_script:
  - npm run coveralls
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
cache:
  yarn: true
  directories:
    - node_modules
services:
  - postgresql
  - redis-server
